#!/bin/sh --
set -ue; export POSIXLY_CORRECT=1
# BY: Jumps Are Op. (jumpsareop@gmail.com)
# LICENSE: GPLv3-or-later

# OUTPUT FORMAT:
# title (optional if description is provided)
# author (optional)
# category (optional)
# comments (optional)
# guid (optional)
# link (optional)
# pubDate (optional)
# description (in html) (optional if title is provided)
# ... description continue to the rest of the output ...

: "${LINK:=https://jumps.neocities.org/blog}${PUBLIC:=public}"
inputprefix=$PUBLIC/blog/

ised(){ printf %s "$input" | sed -n "/$1/{ s#$2#$3#p; q;}; \$s/.*/\n/p";}
frommeta(){
	for arg;do
		ised '<meta name="'"$arg"'" content="[^"]*">' \
		'<meta name="'"$arg"'" content="\(\(\"\|[^"]\)*\)">' '\1'
	done
}
input=$(cat "$@")

# title
ised '<title>.*<\/title>' '<title>\(.*\)</title>' '\1'

frommeta author category comments
# GUID (Global Unique IDentifier) should be unique for every blog
# the easiest way to do this is to use the blog's link
printf %s\\n "${2#"$inputprefix"}" "$LINK/${2#"$inputprefix"}"

frommeta pubDate

# description
printf %s "$input" |
	sed -n '/<div class="container">/,/<\/div> <!-- container -->/p' |
	sed '1d; $d'
