#!/bin/sh -ue
# shellcheck disable=SC2223
# Made by jumps are op
# This software is under GPL version 3 and comes with ABSOLUTELY NO WARRANTY

# Warper around gensite.sh
: "${DRYRUN=}"

# Configuration
: "${CONFIG_CONTENTDIR:=content}${CONFIG_STATICDIR:=static}"
: "${CONFIG_PUBLICDIR:=public}${CONFIG_HEADER:=header}${CONFIG_FOOTER:=footer}"
: "${CONFIG_PARSERS:=parsers}${CONFIG_MKDIRARGS=}${CONFIG_CPARGS=}"

# Check for GNU's -v
[ "$(mkdir 2>&1)" = "mkdir: missing operand
Try 'mkdir --help' for more information." ] &&
	CONFIG_MKDIRARGS="$CONFIG_MKDIRARGS -v"
[ "$(cp 2>&1)" = "cp: missing file operand
Try 'cp --help' for more information." ] &&
	CONFIG_CPARGS="$CONFIG_CPARGS -v"

rm -rf -- "$CONFIG_PUBLICDIR"
export CONFIG_CONTENTDIR CONFIG_STATICDIR CONFIG_PUBLICDIR CONFIG_HEADER \
	CONFIG_FOOTER CONFIG_PARSERS CONFIG_MKDIRARGS CONFIG_CPARGS
gensite.sh

# RSS configuration
: "${TITLE:=Jumps Feed}${DESCRIPTION:=My feeds}"
: "${LINK:=https://jumps.neocities.org}${CATS=}"
: "${COPYRIGHT:=Copyright (C) 2023 Jumps are op (jumpsareop@gmail.com)}"
: "${IMG=}${I_LINK=}${I_TITLE=}${I_URL=}${I_DESC=}${I_HEIGHT=}${I_WIDTH=}"
: "${LANGUAGE:=en-us}${PUB_DATE=}${LAST_BUILD_DATE=}"
: "${MANAGING_EDITOR:=jumpsareop@gmail.com}${EXTRACTOR:=extractor}"
: "${LD:=${IFS#??}}${IND_CHAR=  }${CIND=}"
export TITLE DESCRIPTION LINK CATS COPYRIGHT IMG I_LINK I_TITLE I_URL I_DESC \
	I_HEIGHT I_WIDTH LANGUAGE PUB_DATE LAST_BUILD_DATE MANAGING_EDITOR \
	EXTRACTOR LD IND_CHAR CIND
echo "--- Creating RSS feeds ---"
makerss "$CONFIG_PUBLICDIR/blog"/*/ >"$CONFIG_PUBLICDIR/feed.xml"

set +e
if [ ! "$DRYRUN" ];then
	echo "--- Uploading to Neocities.org ---"
	command -v shcities >/dev/null ||
		echo "shcities isn't installed, please install shcities." >&2
	shcities push "$CONFIG_PUBLICDIR"
fi

command -v tree >/dev/null && { echo "Here you go"; tree "$CONFIG_PUBLICDIR";}
