#!/bin/sh --
set -ue; export POSIXLY_CORRECT=1
# BY: Jumps Are Op. (jupmsareop@gmail.com)
# LICENSE: GPLv3-or-later


# Configuration
: "${DRYRUN=}${CONTENT:=content}${STATIC:=static}${PUBLIC:=public}" \
	"${HEADER:=header}${FOOTER:=footer}${PARSERS:=parsers}"

rm -rf -- "$PUBLIC"
export CONTENT STATIC PUBLIC HEADER FOOTER PARSERS
./gensite.sh

# RSS configuration
: "${COPYRIGHT:=Copyright (C) 2023 Jumps Are Op. (jumpsareop@gmail.com)}" \
	"${TITLE:=Jumps Feed}${DESCRIPTION:=My feeds}${CATS=}" \
	"${LINK:=https://jumps.neocities.org}${IMG=}" \
	"${I_LINK=}${I_TITLE=}${I_URL=}${I_DESC=}${I_HEIGHT=}${I_WIDTH=}" \
	"${LANGUAGE:=en-us}${PUB_DATE=}${LAST_BUILD_DATE=}" \
	"${MANAGING_EDITOR:=jumpsareop@gmail.com}${EXTRACTOR:=extractor}" \
	"${LD:=${IFS#??}}${IND_CHAR=  }${CIND=}"
export TITLE DESCRIPTION LINK CATS COPYRIGHT IMG I_LINK I_TITLE I_URL I_DESC \
	I_HEIGHT I_WIDTH LANGUAGE PUB_DATE LAST_BUILD_DATE MANAGING_EDITOR \
	EXTRACTOR LD IND_CHAR CIND
echo "--- Creating RSS feeds ---"
./makerss "$PUBLIC/blog"/*/ >"$PUBLIC/feed.xml"

[ "$DRYRUN" ] || {
	echo "--- Uploading to Neocities.org ---"
	shcities push "$PUBLIC"
}

echo Done.
