#!/bin/sh --
set -eu; export POSIXLY_CORRECT=1
# BY: Jumps Are Op. (jumpsareop@gmail.com)
# LICENSE: GPLv3-or-later

# read title
while read -r line;do
	[ "$line" != --- ] && continue
	while read -r line;do
		case $line in
			---)break 2;;
			[Tt]itle:\ ?*)title=${line#[Tt]itle: };;
			[Aa]uthor:\ ?*)author=${line#[Aa]uthor: };;
			[Cc]ategory:\ ?*)category=${line#[Cc]ategory: };;
			[Cc]omments:\ ?*)comments=${line#[Cc]omments: };;
			[Gg]uid:\ ?*)guid=${line#[Gg]uid: };;
			[Dd]ate:\ ?*)date=${line#[Dd]ate: };;
		esac
	done
done <"$2"

: "${title:=Jump\'s webpage}${author=}${category=}${comments=}${guid=}${date=}"
cat <<-EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1">
${author:+<meta name=\"author\" content=\"$author\">
}${category:+<meta name=\"category\" content=\"$category\">
}${comments:+<meta name=\"comments\" content=\"$comments\">
}${date:+<meta name=\"pubDate\" content=\"$date\">
}<title>$title</title>
<link rel="stylesheet" href="/style.css">
<link rel="shortcut icon" type="image/png" href="/favicon.png">
<link rel="alternate" href="/feed.xml" type="application/atom+xml" title="Jumps Feed">
</head>
<body>
<nav>
 <table width="100%">
  <tbody>
   <tr>
    <th width="70%" align="left"><a href="/">$title</a></li>
    <th width="3%" align="right"><a href="mailto:jumpsareop@gmail.com">Contact</a></li>
    <th width="3%" align="right"><a href="/blog/index.html">Blog</a></li>
    <th width="3%" align="right"><a href="/about.html">About</a></li>
   </tr>
  </tbody>
 </table>
</nav>
<div class="container">
EOF
