#!/bin/sh --
set -ue; export POSIXLY_CORRECT=1
# BY: Jumps Are Op. (jumpsareop@gmail.com)
# LICENSE: GPLv3-or-later

# Current date in YYYY/MM/DD (the superior format)
dir=content/blog/$(date "+%Y/%m/%d")/
mkdir -p "$dir"
blog=$(printf %s "$*" | tr -c '[:alnum:]' '-' | tr -cs '[:alnum:]').jmu
cat >"$dir/$blog" <<-EOF
	---
	Title: $*
	Author: Jumps Are Op (jumpsareop@gmail.com)
	Category: 
	Comments: 
	Date: $(date +"%a, %d %h %Y %T %Z")
	---
EOF

"${EDITOR:-vi}" "$dir/$blog"
