#!/bin/sh -ufe
# Made by jumps are op
# This software is under GPL version 3 and comes with ABSOLUTELY NO WARRANTY
# newblog BLOG NAME
# Add a new blog and edit it using $EDITOR

# Current date in YYYY/MM/DD (the superior format)
date=$(date "+%Y/%m/%d")

# Check for valid "slot"
i=0
while :;do
	[ ! -e "content/blog/$date/$i" ] && break
	i=$((i+1))
done
dir=content/blog/$date/$i
mkdir -p "$dir"
blog=$(printf %s "$*" | sed 's/ /-/g').md
cat >"$dir/$blog" <<-EOF
	---
	title: $*  
	date: $(date)  
	---
EOF

"${EDITOR:-vi}" "$dir/$blog"
